<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Frosty.Ui</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Ui\Languages\en-US.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converters\" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Update="Resources\Ui\Theming\Default\Theme.axaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaXaml>
  </ItemGroup>

</Project>
