<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <OutputPath>$(RELOADEDIIMODS)/FrostyEditor</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- IL Trimming Support for Framework Dependent Apps. Unofficial.
         If you set this to true, trimming will be enabled when you publish the mod.
         Test trimming with: `BuildLinked.ps1` in PowerShell. -->
    <ReloadedILLink>false</ReloadedILLink>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    <EnableAvaloniaXamlCompilation>True</EnableAvaloniaXamlCompilation>
  </PropertyGroup>

  <ItemGroup>
    <ReloadedLinkRoots Include="FrostyEditor" />
    <!-- Add assemblies to be trimmed. You might need to add their dependencies too!  -->
    <!-- <ReloadedLinkAssemblies Include="Reloaded.Memory" /> -->
  </ItemGroup>

  <Import Project="Reloaded.Trimming.targets" />
  <Import Project="Reloaded.Checks.targets" />

  <ItemGroup>
    <None Remove="FrostyEditor.ico" />
    <None Remove="ModConfig.json" />
    <None Remove="Publish.ps1" />
    <None Remove="BuildLinked.ps1" />
    <None Remove="Reloaded.Trimming.targets" />
    <None Remove="Reloaded.Checks.targets" />
    <None Remove="Resources\Editor\Theming\Default\Images\SVGs\ProgramLogo.svg" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\Editor\Theming\Default\Images\ProgramIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Editor\Theming\Default\Images\SVGs\Gear.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Editor\Theming\Default\Images\SVGs\ProgramLogo.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Resources\Editor\Languages\en-US.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <None Include="Preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.1" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrostyModSupport\FrostyModSupport.csproj" />
    <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
    <ProjectReference Include="..\FrostyTypeSdkGenerator\FrostyTypeSdkGenerator\FrostyTypeSdkGenerator.csproj" />
    <ProjectReference Include="..\FrostyUi\FrostyUi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Include="Resources\Editor\Theming\Default\Images.axaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaXaml>
    <AvaloniaXaml Include="Resources\Editor\Theming\Default\Windows.axaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaXaml>
    <AvaloniaXaml Include="Resources\Editor\Theming\Default\Windows\MainWindow.axaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaXaml>
  </ItemGroup>

  <ItemGroup>
    <None Update="Profiles\Anthem.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Battlefield1.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Battlefield4.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\BattlefieldHardline.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\BattlefieldV.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\BF2042.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\DeadSpace.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\DragonAgeInquisition.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa17.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa18.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa19.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa20.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa21.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa22.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa23.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Fifa24.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Madden19.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Madden20.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Madden21.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Madden22.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Madden23.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Mea.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Mec.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\Nfs.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\NFSHeat.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\NFSOnline.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\NFSPayback.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\NfsRivals.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\NFSUnbound.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\PvZ.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\PvZ2.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\PvZ3.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\SWBF1.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\SWBF2.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Profiles\SWS.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
