<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <OutputPath>$(RELOADEDIIMODS)/FrostyEditor</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- IL Trimming Support for Framework Dependent Apps. Unofficial.
         If you set this to true, trimming will be enabled when you publish the mod.
         Test trimming with: `BuildLinked.ps1` in PowerShell. -->
    <ReloadedILLink>false</ReloadedILLink>
  </PropertyGroup>

  <ItemGroup>
    <ReloadedLinkRoots Include="FrostyEditor" />
    <!-- Add assemblies to be trimmed. You might need to add their dependencies too!  -->
    <!-- <ReloadedLinkAssemblies Include="Reloaded.Memory" /> -->
  </ItemGroup>

  <Import Project="Reloaded.Trimming.targets" />
  <Import Project="Reloaded.Checks.targets" />

  <ItemGroup>
    <None Remove="FrostyEditor.ico" />
    <None Remove="ModConfig.json" />
    <None Remove="Profiles\Anthem.json" />
    <None Remove="Profiles\Battlefield1.json" />
    <None Remove="Profiles\Battlefield4.json" />
    <None Remove="Profiles\BattlefieldHardline.json" />
    <None Remove="Profiles\BattlefieldV.json" />
    <None Remove="Profiles\BF2042.json" />
    <None Remove="Profiles\DeadSpace.json" />
    <None Remove="Profiles\DragonAgeInquisition.json" />
    <None Remove="Profiles\Fifa17.json" />
    <None Remove="Profiles\Fifa18.json" />
    <None Remove="Profiles\Fifa19.json" />
    <None Remove="Profiles\Fifa20.json" />
    <None Remove="Profiles\Fifa21.json" />
    <None Remove="Profiles\Fifa22.json" />
    <None Remove="Profiles\Fifa23.json" />
    <None Remove="Profiles\Fifa24.json" />
    <None Remove="Profiles\Madden19.json" />
    <None Remove="Profiles\Madden20.json" />
    <None Remove="Profiles\Madden21.json" />
    <None Remove="Profiles\Madden22.json" />
    <None Remove="Profiles\Madden23.json" />
    <None Remove="Profiles\Mea.json" />
    <None Remove="Profiles\Mec.json" />
    <None Remove="Profiles\Nfs.json" />
    <None Remove="Profiles\NFSHeat.json" />
    <None Remove="Profiles\NFSOnline.json" />
    <None Remove="Profiles\NFSPayback.json" />
    <None Remove="Profiles\NfsRivals.json" />
    <None Remove="Profiles\NFSUnbound.json" />
    <None Remove="Profiles\PvZ.json" />
    <None Remove="Profiles\PvZ2.json" />
    <None Remove="Profiles\PvZ3.json" />
    <None Remove="Profiles\SWBF1.json" />
    <None Remove="Profiles\SWBF2.json" />
    <None Remove="Profiles\SWS.json" />
    <None Remove="Publish.ps1" />
    <None Remove="BuildLinked.ps1" />
    <None Remove="Reloaded.Trimming.targets" />
    <None Remove="Reloaded.Checks.targets" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="FrostyEditor.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Profiles\Anthem.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Battlefield1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Battlefield4.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\BattlefieldHardline.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\BattlefieldV.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\BF2042.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\DeadSpace.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\DragonAgeInquisition.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa17.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa18.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa19.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa20.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa21.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa22.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa23.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Fifa24.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Madden19.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Madden20.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Madden21.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Madden22.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Madden23.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Mea.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Mec.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\Nfs.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\NFSHeat.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\NFSOnline.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\NFSPayback.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\NfsRivals.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\NFSUnbound.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\PvZ.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\PvZ2.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\PvZ3.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\SWBF1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\SWBF2.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Profiles\SWS.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <None Update="Preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.3.1" />
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="9.0.3" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrostyModSupport\FrostyModSupport.csproj" />
    <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
    <ProjectReference Include="..\FrostyTypeSdkGenerator\FrostyTypeSdkGenerator\FrostyTypeSdkGenerator.csproj" />
  </ItemGroup>

</Project>
