<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\new_huffman" />
    <None Remove="TestData\original_huffman" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\new_huffman">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CustomToolNamespace>FrostySdkTest</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Include="TestData\original_huffman">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CustomToolNamespace>FrostySdkTest</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
